// Generated strictly from Agents/TaskPlanner/specs/Overview.md + shared CodeGenSpecs/
// Do not edit manually — update the spec and re-generate

import Foundation
import SwiftSynapseHarness

public enum TaskPlannerError: Error, Sendable {
    case noResponseContent
    case phaseDecompositionFailed
    case synthesisFailedNoResults
}

// MARK: - Tool Definitions

/// Breaks a complex goal into phases with dependencies. Returns a JSON array of phases.
@LLMTool
public struct BreakdownGoal: AgentLLMTool {
    @LLMToolArguments
    public struct Arguments {
        @LLMToolGuide(description: "The complex goal to decompose into phases with dependencies.")
        var goal: String
    }

    public static var isConcurrencySafe: Bool { true }

    public func call(arguments: Arguments) async throws -> ToolOutput {
        let phases: [[String: Any]] = [
            [
                "id": "phase-1",
                "name": "Research & Analysis",
                "description": "Research and analyze: \(arguments.goal)",
                "dependencies": [] as [String]
            ],
            [
                "id": "phase-2",
                "name": "Planning & Design",
                "description": "Create a detailed plan based on research findings.",
                "dependencies": ["phase-1"]
            ],
            [
                "id": "phase-3",
                "name": "Execution & Delivery",
                "description": "Execute the plan and deliver results.",
                "dependencies": ["phase-2"]
            ]
        ]
        let data = try JSONSerialization.data(withJSONObject: phases, options: [.sortedKeys])
        return ToolOutput(content: String(data: data, encoding: .utf8) ?? "[]")
    }
}

/// Prioritizes phases by adding priority scores and determining execution order.
@LLMTool
public struct PrioritizeTasks: AgentLLMTool {
    @LLMToolArguments
    public struct Arguments {
        @LLMToolGuide(description: "JSON array of phases to prioritize.")
        var phases: String
    }

    public static var isConcurrencySafe: Bool { true }

    public func call(arguments: Arguments) async throws -> ToolOutput {
        guard let data = arguments.phases.data(using: .utf8),
              let parsed = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] else {
            return ToolOutput(content: #"{"error":"Invalid phases JSON","prioritized":[]}"#)
        }

        var prioritized: [[String: Any]] = []
        for (index, phase) in parsed.enumerated() {
            var updated = phase
            updated["priority"] = max(100 - (index * 10), 10)
            updated["executionOrder"] = index + 1
            prioritized.append(updated)
        }

        let result: [String: Any] = ["prioritized": prioritized, "totalPhases": prioritized.count]
        let resultData = try JSONSerialization.data(withJSONObject: result, options: [.sortedKeys])
        return ToolOutput(content: String(data: resultData, encoding: .utf8) ?? #"{"prioritized":[]}"#)
    }
}

/// Combines phase results into a unified Markdown plan document.
@LLMTool
public struct SynthesizeResults: AgentLLMTool {
    @LLMToolArguments
    public struct Arguments {
        @LLMToolGuide(description: "JSON map of phase ID to result content.")
        var phaseResults: String
    }

    public static var isConcurrencySafe: Bool { true }

    public func call(arguments: Arguments) async throws -> ToolOutput {
        guard let data = arguments.phaseResults.data(using: .utf8),
              let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return ToolOutput(content: "# Plan\n\nNo results available.")
        }

        var markdown = "# Unified Plan\n\n## Overview\n\nThis plan synthesizes results from \(parsed.count) phase(s).\n\n"
        for key in parsed.keys.sorted() {
            markdown += "## \(key)\n\n"
            if let stringValue = parsed[key] as? String {
                markdown += "\(stringValue)\n\n"
            } else {
                markdown += "Result: \(String(describing: parsed[key]!))\n\n"
            }
        }
        markdown += "---\n\n*Plan generated by TaskPlanner agent.*\n"
        return ToolOutput(content: markdown)
    }
}

// MARK: - Agent

@SpecDrivenAgent
public actor TaskPlanner {
    private let config: AgentConfiguration
    /// Optional hook pipeline for event interception.
    public private(set) var hooks: AgentHookPipeline?

    /// Sets the hook pipeline for event interception.
    public func setHooks(_ hooks: AgentHookPipeline) { self.hooks = hooks }

    private static let maxToolIterations = 10

    public init(configuration: AgentConfiguration) throws {
        self.config = configuration
    }

    public func execute(goal: String) async throws -> String {
        let client = try config.buildClient()

        let tools = ToolRegistry()
        tools.register(BreakdownGoal())
        tools.register(PrioritizeTasks())
        tools.register(SynthesizeResults())

        let systemPrompt = "You are a task planning coordinator. Break complex goals into phases with dependencies, prioritize them, and synthesize results into a unified plan."

        let result = try await AgentToolLoop.run(
            client: client,
            config: config,
            goal: goal,
            tools: tools,
            transcript: _transcript,
            systemPrompt: systemPrompt,
            maxIterations: Self.maxToolIterations,
            hooks: hooks
        )

        guard !result.isEmpty else {
            throw TaskPlannerError.noResponseContent
        }

        return result
    }
}
